export const dish = {
  name: "Chicken Adobo",
  author: "Aling Vicky",
  url: "https://omnivorescookbook.com/wp-content/uploads/2018/08/1807_Chicken-Adobo_001.jpg",
  duration: 30,
  servings: 4,
  ingredients: [
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
    { qty: 1, ing: "Chicken" },
  ],
};
